// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_api.Data;

#nullable disable

namespace todo_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220605233720_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("todo_api.Models.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            Name = "Important"
                        },
                        new
                        {
                            PriorityId = 2,
                            Name = "Medium important"
                        },
                        new
                        {
                            PriorityId = 3,
                            Name = "Not very important"
                        });
                });

            modelBuilder.Entity("todo_api.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 6, 5, 23, 37, 20, 424, DateTimeKind.Utc).AddTicks(8166),
                            Description = "Łazienka, sypialnia, kuchnia, salon",
                            IsCompleted = false,
                            Name = "Odkurzyć",
                            PriorityId = 2
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 6, 5, 23, 37, 20, 424, DateTimeKind.Utc).AddTicks(8169),
                            Description = "Matematyka - planimetria",
                            IsCompleted = false,
                            Name = "Zrobić zadanie",
                            PriorityId = 1
                        });
                });

            modelBuilder.Entity("todo_api.Models.ToDo", b =>
                {
                    b.HasOne("todo_api.Models.Priority", "Priority")
                        .WithMany("ToDos")
                        .HasForeignKey("PriorityId");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("todo_api.Models.Priority", b =>
                {
                    b.Navigation("ToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
